export { default as Home } from './Home';
export { default as About } from './About';
export { default as ServicesPage } from './ServicesPage';
export { default as PortfolioPage } from './PortfolioPage';
export { default as Contact } from './Contact';
export { default as Login } from './Login';
export { default as Signup } from './Signup';
export { default as Blog } from './Blog';
export { default as Single } from './Single';
